-- 001

USE [master]
GO

-- CREATE DATABASE
CREATE DATABASE [MpcWinFormsIoCDataBase]
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET COMPATIBILITY_LEVEL = 140
GO

ALTER DATABASE [MpcWinFormsIoCDataBase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET ARITHABORT OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET RECOVERY FULL 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET  MULTI_USER 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET QUERY_STORE = OFF
GO
ALTER DATABASE [MpcWinFormsIoCDataBase] SET  READ_WRITE 
GO

-- CREATE USER
USE [master]
GO
CREATE LOGIN [MpcWinFormsIoCUser] WITH PASSWORD=N'Mpc123', DEFAULT_DATABASE=[MpcWinFormsIoCDataBase], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [MpcWinFormsIoCDataBase]
GO
CREATE USER [MpcWinFormsIoCUser] FOR LOGIN [MpcWinFormsIoCUser]
GO
ALTER ROLE [db_datareader] ADD MEMBER [MpcWinFormsIoCUser]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [MpcWinFormsIoCUser]
GO
ALTER ROLE [db_owner] ADD MEMBER [MpcWinFormsIoCUser]
GO

-- CREATE Migrations table
USE [MpcWinFormsIoCDataBase]
CREATE TABLE [dbo].[_DbMigrations](
  [Version] [varchar](50) NOT NULL,
  [Description] [varchar](150) NOT NULL,
  [Author] [varchar](150) NOT NULL,
  [MigrationDate] [datetime] NOT NULL,
  CONSTRAINT [PK_DbMigrations] PRIMARY KEY CLUSTERED 
([Version] ASC)) ON [PRIMARY]
GO

USE [MpcWinFormsIoCDataBase]
GO

DECLARE @version varchar(50) = '001';
DECLARE @description varchar(50) = 'Create Database';
DECLARE @author varchar(50) = 'Miguel Costa';

INSERT INTO [dbo].[_DbMigrations]([Version],[Description],[Author],[MigrationDate])
  VALUES (@version,@description,@author,GETDATE())
GO
